version: '3.7'
services:
#docker run -d -p 8000:8000 --name=currency-exchange
#--network=currency-network dvzr032/microservice-currency-exchange:0.1.V
  currency-exchange:
    image: dvzr032/microservice-currency-exchange:0.1.V
    ports:
      - "8000:8000"
    restart: always
    networks:
      - currency-compose-network

  currency-conversion:
    image: dvzr032/microservice-currency-conversion:0.1.V
    ports:
      - "8100:8100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_SERVICE_HOST: http://currency-exchange
    depends_on:
      - currency-exchange
    networks:
      - currency-compose-network

# Networks created
networks:
  currency-compose-network:


##http://localhost:8100/currency-conversion/from/EUR/to/INR/quantity/10
##http://localhost:8000/currency-exchange/from/USD/to/INR